# site properties and page defaults
title: Computational Social Listening Lab | UPenn
description: Data Science x Health & Psychology
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: /csl-lab

# site social media and other links
links:
  email: sharathg@cis.upenn.edu
  google-scholar: 76_hrfUAAAAJ
  github: chandrasg
  twitter: sharathguntuku

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
    - scope:
      type: collabs
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post

collections:
  members:
    output: true
  collabs:
    output: true
  posts:
    output: true

plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

highlighter: rouge
theme: null

sass:
  sass_dir: _styles

include:
  - _styles
  - _scripts

exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

email: sharathg@cis.upenn.edu
github: chandrasg
twitter: sharathguntuku
